workflows:
  ios-release:
    name: iOS Release Build
    scripts:
      - flutter clean
      - echo "Starting iOS Release Build" > build.txt
      - flutter pub get
      - cd ios && rm -rf Pods Podfile.lock .symlinks && pod install --repo-update && cd ..
      - flutter build ipa --release