workflows:
  ios-release:
    name: iOS Release Build
    scripts:
      - flutter clean
      - echo "Starting iOS Release Build" > build.txt
      - flutter pub get
      - cd ios && pod install && cd ..
      - flutter build ipa --release